//
//  AlbumsProtocols.swift
//  Albums
//
//  Created Zibra Coders on 04/05/2020.
//  Copyright © 2020 Fanovic. All rights reserved.
//
//  Template generated by Zibra Co.

import Foundation

protocol AlbumsViewProtocol: class {
    var presenter: AlbumsPresenterProtocol?  { get set }
    func showAlbums()
    func showError(_ error: String)
    
}

protocol AlbumsPresenterProtocol: class {
    var list: [Album]? { get set }
    func getAlbums()
    func onRequestSuccess(_ albums: [Album])
    func onRequestFailure(_ error: String)
    func showPhotosViewController(with id: Int)
}

protocol AlbumsInteractorProtocol: class {
    var presenter: AlbumsPresenterProtocol?  { get set }
    func fetch()
}

protocol AlbumsRouterProtocol: class {
    func pushPhotoViewController(with id: Int)
}
