//
//  AlbumsProtocols.swift
//  Albums
//
//  Created Zibra Coders on 04/05/2020.
//  Copyright © 2020 Fanovic. All rights reserved.
//
//  Template generated by Zibra Co.

import Foundation

protocol AlbumsViewProtocol: class {
    var presenter: AlbumsPresenterProtocol?  { get set }
}

protocol AlbumsPresenterProtocol: class {
}

protocol AlbumsInteractorProtocol: class {
    var presenter: AlbumsPresenterProtocol?  { get set }
}

protocol AlbumsRouterProtocol: class {
}
