//
//  AlbumsModule.swift
//  Albums
//
//  Created Zibra Coders on 04/05/2020.
//  Copyright © 2020 Fanovic. All rights reserved.
//
//  Template generated by Zibra Co.

import UIKit

class AlbumsModule {

    static func build() -> UIViewController {        
        let view = AlbumsViewController()
        let presenter = AlbumsPresenter()
        let interactor = AlbumsInteractor()
        let router = AlbumsRouter()

        presenter.view = view
        presenter.router = router
        presenter.interactor = interactor
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }    
}
