//
//  AlbumsViewController.swift
//  Albums
//
//  Created Zibra Coders on 04/05/2020.
//  Copyright © 2020 Fanovic. All rights reserved.
//
//  Template generated by Zibra Co.
//

import UIKit

class AlbumsViewController: UIViewController, AlbumsViewProtocol {

    @IBOutlet weak var tableView: UITableView!
    
	var presenter: AlbumsPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        title = "Album list"
        configureTableView()
    }
    override func viewDidAppear(_ animated: Bool) {
        updateTableView()
    }
    
    func configureTableView() {
        tableView.delegate = self
        tableView.dataSource = self
        tableView.register(UINib(nibName: "AlbumTableViewCell", bundle: nil), forCellReuseIdentifier: "AlbumCell")
    }
    
    func showAlbums() {
        tableView.reloadData()
    }
    
    func showError(_ error: String) {
        
    }
    
    func updateTableView() {
        presenter?.getAlbums()
    }

}

extension AlbumsViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return presenter?.list?.count ?? 0
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "AlbumCell") as! AlbumTableViewCell
        if let list = presenter?.list {
            cell.configure(with: list[indexPath.section])
        }
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if let album = presenter?.list?[indexPath.section] {
            self.presenter?.showPhotosViewController(with: album.id)
        }
    }
}
