//
//  AlbumsInteractor.swift
//  Albums
//
//  Created Zibra Coders on 04/05/2020.
//  Copyright © 2020 Fanovic. All rights reserved.
//
//  Template generated by Zibra Co.
//

import UIKit
import PromiseKit

class AlbumsInteractor: AlbumsInteractorProtocol {
    weak var presenter: AlbumsPresenterProtocol?
    
    func fetch() {
        firstly {
            AlbumService.fetch()
        }.done {albums in
            self.presenter?.onRequestSuccess(albums)
        }.catch { error in
            self.presenter?.onRequestFailure(error.localizedDescription)
        }
        
    }
    
    
}
