//
//  PhotosInteractor.swift
//  Albums
//
//  Created Zibra Coders on 05/05/2020.
//  Copyright © 2020 Fanovic. All rights reserved.
//
//  Template generated by Zibra Co.
//

import UIKit
import PromiseKit

class PhotosInteractor: PhotosInteractorProtocol {

    weak var presenter: PhotosPresenterProtocol?
    
    func fetch(with id: Int) {
        firstly {
            PhotoService.fetch(with: id)
        }.done { list in
            self.presenter?.onSuccessRequest(list)
        }.catch { error in
            self.presenter?.onFailureRequest(error.localizedDescription)
        }
    }
    
}
