//
//  PhotosRouter.swift
//  Albums
//
//  Created Zibra Coders on 05/05/2020.
//  Copyright © 2020 Fanovic. All rights reserved.
//
//  Template generated by Zibra Co.

import UIKit

class PhotosRouter: PhotosRouterProtocol {
    weak var viewController: UIViewController?
}
