//
//  AlbumsRouter.swift
//  Albums
//
//  Created Zibra Coders on 04/05/2020.
//  Copyright © 2020 Fanovic. All rights reserved.
//
//  Template generated by Zibra Co.

import UIKit

class AlbumsRouter: AlbumsRouterProtocol {
    weak var viewController: UIViewController?
}
