//
//  PhotosPresenter.swift
//  Albums
//
//  Created Zibra Coders on 05/05/2020.
//  Copyright © 2020 Fanovic. All rights reserved.
//
//  Template generated by Zibra Co.

import UIKit

class PhotosPresenter: PhotosPresenterProtocol {

    weak var view: PhotosViewProtocol?
    var interactor: PhotosInteractorProtocol?
    var router: PhotosRouterProtocol?
    var selectedAlbum: Int?
    
    var list: [Photo]?
    
    func getPhotos() {
        guard let id = selectedAlbum else {
            self.view?.showError("I havent album id!")
            return
        }
        interactor?.fetch(with: id)
    }
    
    func onSuccessRequest(_ photos: [Photo]) {
        list = photos
        view?.showPhotos()
    }
    
    func onFailureRequest(_ error: String) {
        view?.showError(error)
    }
}
